# CI for PayID.org
#

stages:
  - publish
  - deploy

variables:
  GCR_PROJECT_ID: xpring-dev-sandbox
  GCLOUD_PROJECT_ID: xpring-dev-sandbox
  CLUSTER_NAME: poc1-cluster
  CLUSTER_REGION: us-central1
  RELEASE_NAME: payidorg
  RELEASE_ENV: dev
  CICD_ICON: https://i.imgur.com/nxYui1j.png
  INSTALL_XPRING_PROXY: "false"

include:
  - project: 'xpring/xpring-ci-templates'
    file: '/templates/build_for_gcr.yml'

# Build a docker image and push it to the GCR associated with $GCLOUD_PROJECT_ID
publish:
  stage: publish
  extends: .publish
  variables:
    GCLOUD_PROJECT_ID: $GCR_PROJECT_ID

# This is a template that is used below. It does not do anything by itself
.deploy_payidorg:
  extends: .deploy
  needs: ["publish"]
  when: manual
  script:
    - export IMAGE_UID="$(cat image_uid.meta.txt)"
    - mkdir dependency_charts
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.in.xpring.tech/xpring/xpring_nginx.git dependency_charts/xpring_nginx
    - helm dep update ./charts
    - kubectl create namespace ${RELEASE_NAME}-${RELEASE_ENV} || true
    - helm upgrade --install --namespace ${RELEASE_NAME}-${RELEASE_ENV}
        --set releaseEnv=$RELEASE_ENV
        --set replicas=$REPLICAS
        --set releaseImage="gcr.io/$GCR_PROJECT_ID/$CI_PROJECT_NAME:$IMAGE_UID"
        --set proxyng.domainName="${FULL_DNS_NAME}"
        --set proxyng.proxiedService="http://${RELEASE_NAME}-${RELEASE_ENV}:80"
        --set proxyng.replicaCount=$PROXY_REPLICAS
        --set proxyng.install=$INSTALL_XPRING_PROXY
        ${RELEASE_NAME}-${RELEASE_ENV} ./charts

deploy to dev:
  stage: deploy
  extends: .deploy_payidorg
  variables:
    RELEASE_ENV: dev
    FULL_DNS_NAME: dev.payid.org
    INSTALL_XPRING_PROXY: "true"
    REPLICAS: 1
    PROXY_REPLICAS: 1

deploy to stage:
  stage: deploy
  extends: .deploy_payidorg
  variables:
    RELEASE_ENV: stage
    FULL_DNS_NAME: stage.payid.org
    REPLICAS: 2
    PROXY_REPLICAS: 2

# Prod is being deployed to a different GCP project and cluster
deploy to prod:
  stage: deploy
  extends: .deploy_payidorg
  variables:
    RELEASE_ENV: prod
    GCLOUD_PROJECT_ID: xpring-testnet
    CLUSTER_NAME: xpring-testnet-cluster01
    CLUSTER_REGION: us-central1
    FULL_DNS_NAME: payid.org
    REPLICAS: 4
    PROXY_REPLICAS: 4
