apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: public
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: {{ .Release.Name }}-certificate
spec:
  domains:
    - {{ .Values.releaseEnv }}.{{ .Values.publicdomain }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    networking.gke.io/managed-certificates: {{ .Release.Name }}-certificate
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.releaseEnv }}.{{ .Values.publicdomain }}
spec:
  backend:
    serviceName: {{ .Release.Name }}
    servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.releaseImage }}
        livenessProbe:
          httpGet:
              path: /
              port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
              path: /
              port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        name: {{ .Release.Name }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: public
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
